#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-EMAC
version:      1.1
version_from: EMAC.pm
installdirs:  site
requires:
    Crypt::CBC:                    2.08
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
